# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: apitally
  version: "0.20.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apitally-${{ version }}.tar.gz
  sha256: c92f45dd89e397d0aaa56f6bb4a76977208840485ad888f3657f97304d1715bf

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - backoff >=2.0.0
    - typing-extensions >=4.0.0

tests:
  - python:
      imports:
        - apitally
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Simple API monitoring & analytics for REST APIs built with FastAPI, Flask, Django, Starlette, Litestar and BlackSheep.
  homepage: https://apitally.io/
  repository: https://github.com/apitally/apitally-py
  documentation: https://docs.apitally.io/introduction
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
